import { watch } from "node:fs";
import { exists, mkdir } from "node:fs/promises";
import { bundleAsync } from "lightningcss";
import { dark, generateBlock, light, validatePaletteConsistency } from "./token";

const ENTRY = `${import.meta.dir}/styles.css`;
const OUT = "./dist/styles.css";
const GENERATED = `${import.meta.dir}/helpers/color-mode.generated.css`;
const isWatch = process.argv.includes("--watch");

async function ensureDir(path: string) {
  if (!(await exists(path))) {
    await mkdir(path, { recursive: true });
  }
}

function generateTokens(): string {
  const errors = validatePaletteConsistency();
  if (errors.length > 0) {
    console.error("Token validation errors:");
    for (const e of errors) console.error(`  ✗ ${e}`);
    process.exit(1);
  }

  const lightDefault = generateBlock(light, "default");
  const lightInverted = generateBlock(light, "inverted");
  const darkDefault = generateBlock(dark, "default");
  const darkInverted = generateBlock(dark, "inverted");

  const css = `/* Generated by build.ts from token.ts — do not edit */

/* ── Light, default ──────────────────────────────── */
:root,
color-mode {
${indent(lightDefault, 2)}
}

/* ── Light, inverted ─────────────────────────────── */
color-mode[inverted] {
${indent(lightInverted, 2)}
}

/* ── Dark, default ───────────────────────────────── */
@media (prefers-color-scheme: dark) {
  :root,
  color-mode:not([inverted]) {
${indent(darkDefault, 4)}
  }

  /* ── Dark, inverted ──────────────────────────── */
  color-mode[inverted] {
${indent(darkInverted, 4)}
  }
}
`;

  return css;
}

function indent(css: string, spaces = 4): string {
  const prefix = " ".repeat(spaces);
  return css
    .split("\n")
    .map((line) => (line.trim() ? prefix + line : line))
    .join("\n");
}

async function build() {
  const start = performance.now();

  // Step 1: Generate color-mode token CSS
  const generated = generateTokens();
  await Bun.write(GENERATED, generated);
  console.log(`Generated color-mode.generated.css`);

  // Step 2: Bundle with Lightning CSS
  const { code, warnings } = await bundleAsync({
    filename: ENTRY,
    errorRecovery: false,
  });

  for (const warning of warnings) {
    console.warn(
      `⚠ ${warning.message} (${warning.loc?.filename}:${warning.loc?.line}:${warning.loc?.column})`,
    );
  }

  await ensureDir("./dist");
  await Bun.write(OUT, code);
  console.log(`Built styles.css in ${Math.round(performance.now() - start)}ms`);
}

// Initial build
await build();

if (isWatch) {
  console.log("Watching for changes...");

  const watcher = watch(`${import.meta.dir}`, { recursive: true }, (_event, filename) => {
    if (
      filename?.endsWith(".css") &&
      !filename.startsWith("dist/") &&
      filename !== "helpers/color-mode.generated.css"
    ) {
      build().catch(console.error);
    }
    if (filename === "token.ts") {
      build().catch(console.error);
    }
  });

  process.on("SIGINT", () => {
    watcher.close();
    process.exit(0);
  });
}
