export interface GeneratedConfig {
  /** Absolute path to the generated CSS file. */
  output: string;
  /** Returns the complete file contents, including the "Generated by" header. */
  generate(): string;
}

/** Indents each non-empty line by the given number of spaces. */
export function indent(css: string, spaces = 2): string {
  const prefix = " ".repeat(spaces);
  return css
    .split("\n")
    .map((line) => (line.trim() ? prefix + line : line))
    .join("\n");
}
