import type { GeneratedConfig } from "../generated";
import { indent } from "../generated";

const steps = ["4xs", "3xs", "2xs", "xs", "s", "m", "l", "xl", "2xl", "3xl"];
const pairs = ["4xs-3xs", "3xs-2xs", "2xs-xs", "xs-s", "s-m", "m-l", "l-xl", "xl-2xl", "2xl-3xl"];
const tokens = [...steps, ...pairs];

/** [class sign, class suffix, css value] */
type Value = ["" | "-", string, string];

const zero: Value = ["", "0", "0"];
const auto: Value = ["", "auto", "auto"];
const positive: Value[] = tokens.map((t) => ["", t, `var(--spacing-${t})`]);
const negative: Value[] = tokens.map((t) => ["-", t, `calc(var(--spacing-${t}) * -1)`]);

/** [class prefix, css property suffix] */
type Side = [string, string];

const layers: Record<string, Side[]> = {
  all: [["", ""]],
  axes: [
    ["x", "-inline"],
    ["y", "-block"],
  ],
  sides: [
    ["l", "-inline-start"],
    ["r", "-inline-end"],
    ["t", "-block-start"],
    ["b", "-block-end"],
  ],
};

const boxes = [
  { prefix: "m", property: "margin", values: [auto, zero, ...positive, ...negative] },
  { prefix: "p", property: "padding", values: [zero, ...positive] },
];

/** [class prefix, css property, class suffix for zero] */
const gaps = [
  ["gap", "gap", "none"],
  ["gap-row", "row-gap", "none"],
  ["gap-column", "column-gap", "0"],
];

const rule = (selector: string, declaration: string) => `.${selector} {\n  ${declaration}\n}`;
const layer = (name: string, rules: string[]) =>
  `@layer ${name} {\n${indent(rules.join("\n\n"), 2)}\n}`;

const boxRules = (box: (typeof boxes)[number], sides: Side[]) =>
  box.values.flatMap(([sign, suffix, value]) =>
    sides.map(([key, prop]) =>
      rule(`${sign}${box.prefix}${key}-${suffix}`, `${box.property}${prop}: ${value}`),
    ),
  );

const gapRules = gaps.flatMap(([prefix, property, zeroSuffix]) => [
  ...[...steps].reverse().map((s) => rule(`${prefix}-${s}`, `${property}: var(--spacing-${s})`)),
  rule(`${prefix}-${zeroSuffix}`, `${property}: 0`),
]);

function generate(): string {
  return `${[
    "/* Generated by build.ts from spacing.config.ts — do not edit */",
    // Later layers win regardless of source order: sides (pt-*) beat axes (px-*) beat all (p-*).
    "@layer spacing.all, spacing.axes, spacing.sides;",
    ...boxes.flatMap((box) =>
      Object.entries(layers).map(([name, sides]) => layer(`spacing.${name}`, boxRules(box, sides))),
    ),
    layer("spacing.gap", gapRules),
  ].join("\n\n")}\n`;
}

const config: GeneratedConfig = {
  output: `${import.meta.dir}/spacing.generated.css`,
  generate,
};

export default config;
